### ISSUE TITLE
Try introducing phpstan

### ISSUE THREAD

**Issue by szepeviktor** [Brain-WP/BrainFaker#2]
`phpstan.neon.dist`

```yaml
#$ composer require --dev szepeviktor/phpstan-wordpress phpstan/phpstan-shim phpstan/phpstan-mockery
#$ vendor/bin/phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: 4
#    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
        - %currentWorkingDirectory%/inc/
    ignoreErrors:
```
